jms_translation:
  locales: ['pl']
  source_language: 'en'
  configs:
    app:
      dirs: ["%kernel.root_dir%/../templates", "%kernel.root_dir%/../src"]
      output_dir: "%kernel.root_dir%/../src/translations"